// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import ModalUserController from "./modal_user_controller"
application.register("modal-user", ModalUserController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import AutohideFlashController from "./autohide_flash_controller"
application.register("autohide-flash", AutohideFlashController)

import AlertController from "./alert_controller"
application.register("alert", AlertController)

import CommentReplyController from "./comment_reply_controller"
application.register("comment-reply", CommentReplyController)

import ObjectAuthorController from "./object_author_controller"
application.register("object-author", ObjectAuthorController)

import CardsUtilController from "./cards_util_controller"
application.register("cards-util", CardsUtilController)

import CurrentPageController from "./current_page_controller"
application.register("current-page", CurrentPageController)
