// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AlertController from "./alert_controller.js"
application.register("alert", AlertController)

import AnimateSearchController from "./animate_search_controller.js"
application.register("animate-search", AnimateSearchController)

import AutohideFlashController from "./autohide_flash_controller.js"
application.register("autohide-flash", AutohideFlashController)

import CardsUtilController from "./cards_util_controller.js"
application.register("cards-util", CardsUtilController)

import CommentReplyController from "./comment_reply_controller.js"
application.register("comment-reply", CommentReplyController)

import CurrentPageController from "./current_page_controller.js"
application.register("current-page", CurrentPageController)

import DropdownController from "./dropdown_controller.js"
application.register("dropdown", DropdownController)

import DropdownSortController from "./dropdown_sort_controller.js"
application.register("dropdown-sort", DropdownSortController)

import LikesController from "./likes_controller.js"
application.register("likes", LikesController)

import ModalController from "./modal_controller.js"
application.register("modal", ModalController)

import ModalUserController from "./modal_user_controller.js"
application.register("modal-user", ModalUserController)

import ObjectAuthorController from "./object_author_controller.js"
application.register("object-author", ObjectAuthorController)

import SearchController from "./search_controller.js"
application.register("search", SearchController)
